#
###################################
# Site wide configuration
####################################
#
title: 中国古代诗词歌赋
email: cleveben@gmail.com
description: 中国古典文学，诗词歌赋，唐诗宋词
url: https://www.iexpp.com # the base hostname & protocol for your site
keywords: ["李白", "唐诗", "杜甫", "宋词", "诗词歌赋", "古典文学"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          Asia/Beijing
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: 中国古代诗词歌赋
  avatar: avatar.jpg
  job: 
  bio: 
  email: #username
  disqus-shortname: #username
  twitter:  #username
  facebook: #username
  google:
    plus: #username
    analytics: 
    verify:
    ad-client: ca-pub-4417209362374533
    ad-slot:
  bing-verify:
  github: #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
  telegram: #username
